// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcg4X6c6ZuaDncuV3i1RdO-hJAbFgrWMw',
    appId: '1:500411965384:web:a976368afbc4bc7aefaafd',
    messagingSenderId: '500411965384',
    projectId: 'logiscan-d0daf',
    authDomain: 'logiscan-d0daf.firebaseapp.com',
    storageBucket: 'logiscan-d0daf.firebasestorage.app',
    measurementId: 'G-T534269VXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFiqpEBd6qnd_rVk6bOTxlWbmHVpXmldY',
    appId: '1:500411965384:android:e7c846c837eb7467efaafd',
    messagingSenderId: '500411965384',
    projectId: 'logiscan-d0daf',
    storageBucket: 'logiscan-d0daf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMpgEU3L_aypzM_tE5kRQAK_NR79fWz5o',
    appId: '1:500411965384:ios:7e0d56538fc7b2f3efaafd',
    messagingSenderId: '500411965384',
    projectId: 'logiscan-d0daf',
    storageBucket: 'logiscan-d0daf.firebasestorage.app',
    iosBundleId: 'com.gbi-logistics.logiscan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMpgEU3L_aypzM_tE5kRQAK_NR79fWz5o',
    appId: '1:500411965384:ios:7e0d56538fc7b2f3efaafd',
    messagingSenderId: '500411965384',
    projectId: 'logiscan-d0daf',
    storageBucket: 'logiscan-d0daf.firebasestorage.app',
    iosBundleId: 'com.gbi-logistics.logiscan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcg4X6c6ZuaDncuV3i1RdO-hJAbFgrWMw',
    appId: '1:500411965384:web:85d1eec830f89c83efaafd',
    messagingSenderId: '500411965384',
    projectId: 'logiscan-d0daf',
    authDomain: 'logiscan-d0daf.firebaseapp.com',
    storageBucket: 'logiscan-d0daf.firebasestorage.app',
    measurementId: 'G-T3HWDM9E5L',
  );
}
